CREATE TABLE inf_diario (
ID SERIAL PRIMARY KEY NOT NULL,
TP_FUNDO VARCHAR(2) NOT NULL,
CNPJ_FUNDO VARCHAR(20) NOT NULL,
DT_COMPTC DATE NOT NULL,
VL_TOTAL NUMERIC(17,2),
VL_QUOTA NUMERIC(27,12),
VL_PATRIM_LIQ NUMERIC(17,2),
CAPTC_DIA NUMERIC(17,2),
RESG_DIA NUMERIC(17,2),
NR_COTST NUMERIC(10,0)
);
